# Displayname template for SMS users.
# {{.FullName}} - Full name provided by the phone
# {{.FirstName}} - First name provided by the phone
# {{.PhoneNumber}} - Formatted phone number provided by the phone
displayname_template: "{{or .FullName .PhoneNumber}}"
# Settings for how the bridge appears to the phone.
device_meta:
    # OS name to tell the phone. This is the name that shows up in the paired devices list.
    os: mautrix-gmessages
    # Browser type to tell the phone. This decides which icon is shown.
    # Valid types: OTHER, CHROME, FIREFOX, SAFARI, OPERA, IE, EDGE
    browser: OTHER
    # Device type to tell the phone. This also affects the icon, as well as how many sessions are allowed simultaneously.
    # One web, two tablets and one PWA should be able to connect at the same time.
    # Valid types: WEB, TABLET, PWA
    type: TABLET
# Should the bridge aggressively set itself as the active device if the user opens Google Messages in a browser?
# If this is disabled, the user must manually use the `set-active` command to reactivate the bridge.
aggressive_reconnect: false
# Number of chats to sync when connecting to Google Messages.
initial_chat_sync_count: 25
